export const ActionTypes = {
    GET_USERS : "GET_USERS",
    ADD_USER : "ADD_USER",
    UPDATE_MODAL_V:"UPDATE_MODAL_V",
    VIEW_MODAL_V:"VIEW_MODAL_V",
    DETAILED_USER:"DETAILED_USER",
    ADD_USER_MODAL_V:"ADD_USER_MODAL_V",
    ADD_TODO_MODAL_V:"ADD_TODO_MODAL_V",
    LAST_DELETED_USER:"LAST_DELETED_USER",
    DELETE_MODAL_V:"DELETE_MODAL_V",
    DELETE_USER_ID:"DELETE_USER_ID"
};